#!/usr/bin/env bash
#installs Nginx, sets it so that /redirect_me redirects to another page, there is a custom 404 page, and HTTP response contains a custom header
sudo apt-get update
sudo apt-get -y install haproxy
sudo printf "\n frontend holberton
    bind *:80
    mode http
    default_backend web_servers
backend web_servers
    mode http
    balance roundrobin
    server 4636-web-01  3.80.82.238
    server 4636-web-02  54.91.192.218 | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
